version: 6.0.{build}
branches:
  only:
  - master
  - development  
skip_tags: true
max_jobs: 1
image: Visual Studio 2017
configuration: Release
environment:
  NUGET_API_KEY:
    secure: CyBw6is7V/vUqMgcZ0wozOYlF/q0Yl6M6f/OKrpSBzlvg9Fp5tllMw2ac2Tl9AAD
build: off    
build_script:
- ps: >-
    $packVersion = $env:APPVEYOR_BUILD_VERSION

    if ($env:APPVEYOR_REPO_BRANCH -ieq "development") {
        $packVersion += "-beta"
    }

    dotnet pack -c "Release" -p:Version=$packVersion

    dotnet nuget push ".\PetaPoco\bin\Release\*.nupkg" -k "$($env:NUGET_API_KEY)" -s "https://www.nuget.org/api/v2/package"
test: off